Docker Dektop Example
camptocamp/helm-geoserver-cloud pull request #175
Opened 2024-01-28 22:14 UTC by 1ly1mk

This PR add docker desktop example for windows (can be also deployed in linux docker) with minimal user configuration. I believe that community will find this PR helpful.

2024-02-05 08:57 UTC, danduk82 commented
Hi @1ly1mk ,
could you please apply the suggested patch from pre-commit and create a new PR? Please use another branch name instead of `master` , this creates some side effects with the CI.

2024-02-05 08:57 UTC, danduk82 requested changes
Hi @1ly1mk ,
could you please apply the suggested patch from pre-commit and create a new PR? Please use another branch name instead of `master` , this creates some side effects with the CI.

2024-02-06 13:41 UTC, danduk82 approved these changes
Thanks @1ly1mk  for the contribution :)

2024-02-06 13:41 UTC, merged

2024-02-07 14:02 UTC, 1ly1mk commented
Thank you @danduk82 , will try to create few more PR with windows based examples.

2024-02-07 17:58 UTC, 1ly1mk commented on examples/docker-dektop/README.md
> + helm upgrade --install --values=.\values.yaml ogsdocker .
@danduk82 just noticed, there typo with the release name it should be "ogsv1"
helm upgrade --install --values=.\values.yaml ogsv1 .