HPA example. Upgrade helm-application dependency
camptocamp/helm-geoserver-cloud pull request #254
Opened 2024-10-15 20:15 UTC by jemacchi

- HPA example. 
- Upgrade helm-application dependency.

2024-10-16 06:33 UTC, danduk82 approved these changes
:star_struck:

2024-10-16 12:12 UTC, groldan commented
@danduk82 you beat me I was going to provide a couple improvements. Nevermind, will create a seprate pr

2024-10-16 15:12 UTC, groldan approved these changes
* Made some improvements to the HPA example's README. View it rendered here: https://github.com/camptocamp/helm-geoserver-cloud/blob/hpa/examples/pgconfig-wms-hpa/README.md
* fixed a couple mispelled commands
* changed the stress script to use Apache Benchmark

2024-10-17 06:59 UTC, danduk82 requested changes
I found just one little typo in the docs

2024-10-17 06:59 UTC, danduk82 commented on examples/pgconfig-wms-hpa/README.md
> +/examples/pgconfig-wms-hpa/init-catalog.sh
the path here should be relative, it's missing a `.` character, so it should be 
```suggestion
./examples/pgconfig-wms-hpa/init-catalog.sh
```

2024-10-17 06:59 UTC, danduk82 commented on examples/pgconfig-wms-hpa/README.md
> +/examples/pgconfig-wms-hpa/init-catalog.sh
ping @groldan

2024-10-17 17:51 UTC, jemacchi reviewed
LGTM

2024-10-17 19:57 UTC, groldan approved these changes

2024-10-18 07:00 UTC, danduk82 approved these changes

2024-10-18 07:00 UTC, merged